server:
  port: 8081
spring:
  application:
    name: hmdp
  profiles:
    active: dev
  datasource:
    # JDBC 连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&useUnicode=true&serverTimezone=UTC
    # DB 凭据
    username: root
    password: zhang1994
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity,com.hmdp.dto # 别名扫描包
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.hmdp: debug
  pattern:
    dateformat: mm:ss.SSS